### ISSUE TITLE
Samples ?

### ISSUE THREAD

**Issue by francqz31** [Wieland3/reference-master#1]
@Wieland3 Do you have any samples before and after the mastering 
how good is this method compared to https://github.com/sergree/matchering

Thanks in advance

**Comment by Wieland3** [comment]
@francqz31 Thank you for the request. I will work on providing some examples to compare different mastering services so you can judge for yourself.

**Comment by Wieland3** [comment]
@francqz31 I put together a short youtube video comparing reference-master, Matchering and Landr on one track. All masters were done with the same reference, "Break the Fall" by Papa Roach.

Let me know what you think. 
https://youtu.be/6kvGeVtv1Cw?feature=shared

My take aways are the following: 
In my opinion the mastering with reference-master is better at preserving the transients from the drums than Matchering, probably due to the use of a clipper. (of course I am biased though)

However I noticed that not all songs get mastered well with my project. I think this is due to the nature of the optimization strategy and how well the song and the reference align in the first place. I think it is crucial with all of these methods to listen carefully after the mastering and decide if it is good.
